name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gh-actions
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: BKW_
        
      - name: Get CW
        run: |
          mkdir CW
          curl -o CW/license.dat -fSL ${{ secrets.CW_LINK }}/license.dat
          curl -o CW/lmgr11.dll -fSL ${{ secrets.CW_LINK }}/lmgr11.dll
          curl -o CW/mwasmeppc.exe -fSL ${{ secrets.CW_LINK }}/mwasmeppc.exe
          curl -o CW/mwcceppc.exe -fSL ${{ secrets.CW_LINK }}/mwcceppc.exe
          curl -o CW/mwldeppc.exe -fSL ${{ secrets.CW_LINK }}/mwldeppc.exe

      - name: Build BKW
        shell: bash
        run: |
          git clone https://github.com/MelgMKW/Pulsar.git Pulsar
          mv CW Pulsar/CW
          cd BKW_
          mv BKW ../Pulsar/BKW
          mv PulsarEngine/Race/200cc.cpp ../Pulsar/PulsarEngine/Race/200cc.cpp
          cd ../Pulsar
          
          rm -rf build
          mkdir build
          
          # Compile CPP
          CW/mwcceppc.exe -I- -i KamekInclude -opt all -inline auto -enum int \
            -proc gekko -fp hard -sdata 0 -sdata2 0 -maxerrors 1 -func_align 4 \
            -c -o "build/kamek.o" "KamekInclude/kamek.cpp"

          compile() {
          find $1 -type f -name '*.cpp' -exec sh -c '
            echo $1
            f=${1##*/}
            CW/mwcceppc.exe -I- -i KamekInclude -i GameSource -i PulsarEngine -i BKW \
              -opt all -inline auto -enum int -proc gekko -fp hard -sdata 0 -sdata2 0 \
              -maxerrors 1 -func_align 4 -c -o build/${f%.cpp}.o $1
            echo -n "build/${f%.cpp}.o " >> objects.txt' sh '{}' ';'
          }
          
          compile BKW
          compile PulsarEngine
          OBJECTS=$(cat objects.txt)
          
          # Link
          echo Linking...
          date -u
          "./KamekLinker/Kamek.exe" "build/kamek.o" $OBJECTS -dynamic -externals="GameSource/symbols.txt" -versions="GameSource/versions.txt" -output-combined=build/Code.pul
          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Code.pul
          path: Pulsar/build/Code.pul
