name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gh-actions
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: BKW_
        
      - name: Get CW
        run: |
          mkdir CW
          curl -o CW/license.dat -fSL ${{ secrets.CW_LINK }}/license.dat
          curl -o CW/lmgr11.dll -fSL ${{ secrets.CW_LINK }}/lmgr11.dll
          curl -o CW/mwasmeppc.exe -fSL ${{ secrets.CW_LINK }}/mwasmeppc.exe
          curl -o CW/mwcceppc.exe -fSL ${{ secrets.CW_LINK }}/mwcceppc.exe
          curl -o CW/mwldeppc.exe -fSL ${{ secrets.CW_LINK }}/mwldeppc.exe

      - name: Build BKW
        shell: cmd
        run: | 
          @echo off
          SETLOCAL EnableDelayedExpansion
          
          git clone https://github.com/MelgMKW/Pulsar.git Pulsar
          move CW Pulsar
          cd BKW_
          move BKW ..\Pulsar
          move /Y PulsarEngine\Race\200cc.cpp ..\Pulsar\PulsarEngine\Race\200cc.cpp
          cd ..\Pulsar
          
          del /F /Q /S build
          mkdir build
          
          SET "ENGINE=.\KamekInclude"
          set "GAMESOURCE=.\GameSource"
          SET "PULSAR=.\PulsarEngine"
          SET "BKW=.\BKW"
          
          :: Change this as necessary depending on where you put CodeWarrior
          SET "CC=CW\mwcceppc.exe"
          
          :: Riivolution Destination (change as necessary)
          SET "RIIVO="
          
          :: Compiler flags and folder
          SET CFLAGS=-I- -i %ENGINE% -i %GAMESOURCE% -i %PULSAR% -i %BKW% ^
            -opt all -inline auto -enum int -proc gekko -fp hard -sdata 0 -sdata2 0 -maxerrors 1 -func_align 4 %cwDWARF%
          SET DEFINE=
          
          if "!CC!" == "" (
              echo You need to specify the path to CodeWarrior by setting the CC variable
              exit /b 1
          )
          
          :: CPP Sources
          SET CPPFILES=
          for /R %BKW% %%f in (*.cpp) do SET "CPPFILES=%%f !CPPFILES!"
          for /R %PULSAR% %%f in (*.cpp) do SET "CPPFILES=%%f !CPPFILES!"
          
          :: Compile CPP
          %CC% %CFLAGS% -c -o "build/kamek.o" "%ENGINE%\kamek.cpp"
          
          SET OBJECTS=
          FOR %%H IN (%CPPFILES%) DO (
              ::echo "Compiling %%H..."
              %CC% %CFLAGS% %DEFINE% -c -o "build/%%~nH.o" "%%H"
              if not errorlevel 0 (
                  echo Compilation error. Aborting script...
                  exit /b 1
              )
              SET "OBJECTS=build/%%~nH.o !OBJECTS!"
          )
          
          :: Link
          echo Linking... %time%
          ".\KamekLinker\Kamek.exe" "build/kamek.o" %OBJECTS% %debug% -dynamic -externals="%GAMESOURCE%/symbols.txt" -versions="%GAMESOURCE%/versions.txt" -output-combined=build\Code.pul
          
          :end
          ENDLOCAL

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Code.pul
          path: Pulsar/build/Code.pul
