name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gh-actions
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get CW
        run: |
          mkdir CW
          curl -o CW/license.dat -fSL https://github.com/Danster64/NSMBWer/raw/05dae4ddf04745d389923670311de437d2df825c/Kamek/tools/license.dat
          curl -o CW/lmgr11.dll -fSL https://github.com/Danster64/NSMBWer/raw/05dae4ddf04745d389923670311de437d2df825c/Kamek/tools/lmgr11.dll
          curl -o CW/mwasmeppc.exe -fSL https://github.com/Danster64/NSMBWer/raw/05dae4ddf04745d389923670311de437d2df825c/Kamek/tools/mwasmeppc.exe
          curl -o CW/mwcceppc.exe -fSL https://github.com/Danster64/NSMBWer/raw/05dae4ddf04745d389923670311de437d2df825c/Kamek/tools/mwcceppc.exe
          curl -o CW/mwldeppc.exe -fSL https://github.com/Danster64/NSMBWer/raw/05dae4ddf04745d389923670311de437d2df825c/Kamek/tools/mwldeppc.exe

      - name: Build BKW
        run: |
          build_actions.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Code.pul
          path: Code.pul
